Custom sort parameters for the 'list clusters' command
giantswarm/gsctl pull request #551
Opened 2020-05-14 16:19 UTC by axbarsan

Closes https://github.com/giantswarm/giantswarm/issues/10811

2020-05-15 18:45 UTC, marians requested changes
Impressive work! 🚀 

Some wishes for improvements:

- The sorting by cluster name and org should use case-insensitive [alphanumerical](http://davekoelle.com/alphanum.html) sorting. There is an implementation of the alphanumerical algorithm in https://github.com/facette/natsort
- The flag info `-s, --sort string       Sort by the given field` should contain the field names that can be used to sort by. Suggestion: `Sort by one of the fields id, o(rganization), n(ame), r(elease), c(reated), d(eleting-since)
- I noticed we don't have any examples in the usage for this command. Could you please add an example using both `--sort` and `--output json`? Potentially also `--selector`.

---

When using `--sort del` without using `--show-deleting`, this error occurs:

```
./gsctl list clusters -e ginger --sort del
Cannot sort by attribute 'del'.
The attribute 'del' does not exist.
You can sort by any of these attributes: id, created, name, organization, release, deleting-since
```

The fact that `deleting-since` appears in the list of possible sort attributes is misleading.

2020-05-18 09:39 UTC, axbarsan commented
> * The sorting by cluster name and org should use case-insensitive [alphanumerical](http://davekoelle.com/alphanum.html) sorting. There is an implementation of the alphanumerical algorithm in https://github.com/facette/natsort

We're now using that algorithm for sorting strings. Thank you for the great find 👍 

> * The flag info `-s, --sort string       Sort by the given field` should contain the field names that can be used to sort by. Suggestion: `Sort by one of the fields id, o(rganization), n(ame), r(elease), c(reated), d(eleting-since)

✅ (I printed `id` as `i(d)` because using `--sort i` works.

> * I noticed we don't have any examples in the usage for this command. Could you please add an example using both `--sort` and `--output json`? Potentially also `--selector`.

✅ 

> When using `--sort del` without using `--show-deleting`, this error occurs:
> 
> ```
> ./gsctl list clusters -e ginger --sort del
> Cannot sort by attribute 'del'.
> The attribute 'del' does not exist.
> You can sort by any of these attributes: id, created, name, organization, release, deleting-since
> ```
> 
> The fact that `deleting-since` appears in the list of possible sort attributes is misleading.

✅ I added the possibility to hide columns, and sorting will not throw any errors even if that column is hidden and the data is not there

2020-05-19 08:52 UTC, marians commented on commands/list/clusters/command.go
> +  gsctl list clusters --sort organization
```suggestion
  gsctl list clusters --sort org
```

Let's hunch users to save some typing :)

2020-05-19 08:58 UTC, marians approved these changes
❤️

2020-05-19 08:58 UTC, merged